### ISSUE TITLE
Large integer lose precision when convert to string

### ISSUE THREAD

**Issue by yongman** [mlua-rs/mlua#183]
As the issue https://github.com/redis/redis/issues/1118 mentioned, when I use mlua I also have the same problem.

I create a lua async function as follows

```
lua.create_async_function(move |_lua, args: Variadic<String>| {
....
}
```

When I call this function in lua script and pass a large integer, such as `9007199254740991` as int not string, I got a converted string value `9.007199254741e+15` in the function.

How can I avoid the convert in mlua?

Thanks.

**Comment by khvzak** [comment]
What Lua version you use? 
Lua 5.1 and Lua >= 5.3 have different behaviour:
```
$ lua5.1 -e 'print(tostring(9007199254740991))'
9.007199254741e+15

$ lua5.4 -e 'print(tostring(9007199254740991))'
9007199254740991
```

When you declare argument as String and then pass a large integer, mlua converts the value in a manner consistent with Lua internal behavior.

See [lua_tolstring ](https://www.lua.org/manual/5.4/manual.html#lua_tolstring) function.

**Comment by yongman** [comment]
@khvzak I am using `luajit` feature, I will try `lua5.4`.

Thanks for your reply.

**Comment by khvzak** [comment]
If you want to implement custom conversion logic for Lua 5.1 then you can declare arguments as `mlua::Value` and do manual coersion:
```
    let f = lua.create_function(|_, x: Value| {
        if let Value::Integer(n) = x {
            println!("{}", n);
        }
        Ok(())
    });
```

The value `9007199254740991 ` fits to 52 bits and mlua losslessly "recognizes" it as an integer.

**Comment by Kyiro** [comment]
Sorry for resurrecting such a dead issue, but I'm facing these issues without even formatting to a string
```
fn main() -> mlua::Result<()> {
    let lua = mlua::Lua::new();
    
    let res = lua.load("419425853714202634").eval::<u64>()?;
    
    println!("{}", res);
    assert_eq!(res, 419425853714202634);
    
    Ok(())
}
```
```
419425853714202624
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `419425853714202624`,
 right: `419425853714202634`', src\main.rs:29:5
 ```

**Comment by khvzak** [comment]
luajit does not support 64 bit integers, maximum is **52 bits.**
An example:
```
$ luajit -e 'print(419425853714202634 == 419425853714202624)'
true
```

**Comment by Kyiro** [comment]
Thanks for the quick response! I wasn't aware that was a thing
