### ISSUE TITLE
Cannot call Lua::create_function with static Lua state

### ISSUE THREAD

**Issue by grahamjameson** [mlua-rs/mlua#334]
```rust
error[E0277]: `*mut lua_State` cannot be shared between threads safely
    --> lua_fun/src/lib.rs:166:17
     |
165  |               WRAPPER.lock().unwrap().lua.create_function(
     |                                         --------------- required by a bound introduced by this call
166  | /                 |_lua, (x, y): (String, String)| {
...
183  | |                 },
     | |_________________^ `*mut lua_State` cannot be shared between threads safely
```

https://github.com/khvzak/mlua/issues/233 was already helpful, but I'm bumping into this issue when trying to create a Lua function from Rust. Ideally those strings could be of type `Function` as well, but if that's not possible I'd be content just to get string so I can look them up instead.

**Comment by khvzak** [comment]
I would suggest to keep reference to function as [`RegistryKey`](https://docs.rs/mlua/latest/mlua/struct.RegistryKey.html) type.
Do you have a full code example?
