### ISSUE TITLE
Hash trait for LuaThread / storing results of threads

### ISSUE THREAD

**Issue by filiptibell** [mlua-rs/mlua#362]
I would like to be able to do something like this:

```rs
struct LuaThreadResults<'lua> {
    inner: HashMap<LuaThread<'lua>, LuaRegistryKey>,
}
```

But this does not work since `LuaThread` does not implement `Hash`.

The use case here would be to store the "latest result" for a thread resumption - this result could be from rust code, `coroutine.resume`, or really just any place a thread is resumed. For this to work with built in libraries like `coroutine.resume` obviously I would need to override those functions, this is fine for me.

Is there a better way to do this? Is it possible to do?

**Comment by khvzak** [comment]
Generally you can use `to_pointer()` (`Value::Thread(thread).to_pointer()`) method for hash calculation. I'll take a look into implementing `Hash` for it.

**Comment by filiptibell** [comment]
> Generally you can use `to_pointer()` (`Value::Thread(thread).to_pointer()`) method for hash calculation. I'll take a look into implementing `Hash` for it.

`to_pointer` works great - I don't even need `Hash` then since a newtype struct and `pointer as usize` will be less overhead. 👍
It would be nice to have pointer conversion directly on `LuaThread` also since right now I have only a ref to a thread and need to clone to put into a `LuaValue` and access this method

**Comment by khvzak** [comment]
> It would be nice to have pointer conversion directly on LuaThread 

Done in 908f37656ac581db796556a9e0847ddab27d3ef9
