### ISSUE TITLE
Unable to compile with musl

### ISSUE THREAD

**Issue by dandyvica** [mlua-rs/mlua#364]
Hi,

First, let me tell you that your crate is an amazing job ! Kudos for such a useful work 👏

I can compile for the `x86_64-unknown-linux-gnu` target, by installing `pks-config` and `lua` dev libs.
But for the` x86_64-unknown-linux-musl` target, compilation fails with:

`  cannot find Lua5.4 using pkg-config: pkg-config has not been configured to support cross-compilation.`

Is it coming from `Lua` lib itself ? Does `mlua` support musl targets ?

Thanks.

**Comment by khvzak** [comment]
You need a musl toolchain, musl version of lua lib and musl version of pkg-config.
mlua does support musl target, you just need to configure your system for cross compilation.
You can try https://github.com/rust-cross/rust-musl-cross project OR install a musl toolchain and build your project with mlua `vendored` feature.

**Comment by dandyvica** [comment]
@khvzak Thanks for your help.
