### ISSUE TITLE
Passing an Rc as an arg to a Function call doesn't drop the strong count

### ISSUE THREAD

**Issue by jo3bingham** [mlua-rs/mlua#368]
```rust
struct Thing;

impl mlua::UserData for Thing {}

fn main() {
    let lua = mlua::Lua::new();

    let thing = std::rc::Rc::new(std::cell::RefCell::new(Thing));
    println!("{}", std::rc::Rc::strong_count(&thing)); // prints "1"

    {
        let t = std::rc::Rc::clone(&thing);

        let func: mlua::Function = lua.load(
            r#"
                function(thing)
                    -- do nothing
                end
        "#).eval().unwrap();
        func.call::<_, ()>(t).unwrap();

        println!("{}", std::rc::Rc::strong_count(&thing)); // prints "2"
    }

    println!("{}", std::rc::Rc::strong_count(&thing)); // prints "2"
}
```

Here's a very basic example that reproduces what I'm seeing. I would expect the last two `println!()` calls to print "1", but that doesn't seem to be the case. Is `lua` still holding the strong reference to `thing`, or am I doing something wrong?

**Comment by khvzak** [comment]
> Is lua still holding the strong reference to thing

Yep, it will release it some time after (this is how Lua GC works).
If you run `lua.gc_collect()?;` before the last print, the refcould will be `1` again.

**Comment by jo3bingham** [comment]
> > Is lua still holding the strong reference to thing
> 
> 
> 
> Yep, it will release it some time after (this is how Lua GC works).
> 
> If you run `lua.gc_collect()?;` before the last print, the refcount will be `1` again.
> 
> 

Ah, I forgot that Lua has to garbage collect. Thanks!
