### ISSUE TITLE
Lua 5.1: cannot create a Lua reference, out of auxiliary stack space

### ISSUE THREAD

**Issue by gptlang** [mlua-rs/mlua#373]
This error only occurs on Lua 5.1 but not on Lua 5.4.

<details>

<summary>
Log
</summary>

```rust

```

</details>

Code: https://github.com/gptlang/lua-tiktoken/blob/07fcbd09382c478b36cf598d6b0c6e62d385ec31/src/lib.rs#L184-L256

Previous issues: https://github.com/mlua-rs/mlua/issues/16

Possible issue: I'm loading a 1.7M table into the binding. Not sure how to avoid this issue

**Comment by khvzak** [comment]
Lua 5.1 has only [8,000](https://www.lua.org/source/5.1/luaconf.h.html#LUAI_MAXCSTACK) stack slots, whereas Lua 5.4 has [1,000,000](https://www.lua.org/source/5.4/luaconf.h.html#LUAI_MAXSTACK) (125 times higher).
To bypass this limitation you can store references to Lua objects in registry (see [`RegistryKey`](https://docs.rs/mlua/latest/mlua/struct.RegistryKey.html))
