### ISSUE TITLE
NixOS breaks luajit compilation

### ISSUE THREAD

**Issue by BIGNARF** [mlua-rs/mlua#374]
I tried compiling an empty project on my NixOS machine with just the "luajit" and "vendored" features. It doesn't compile.

Here's the full compiler error:

Compiling mlua-sys v0.5.1
error: failed to run custom build command for `mlua-sys v0.5.1`

Caused by:
  process didn't exit successfully: `/home/bigpog/nix-is-pain/target/debug/build/mlua-sys-b1026b0ddb76bbdf/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running cd "/home/bigpog/nix-is-pain/target/debug/build/mlua-sys-d87608ae0127735d/out/luajit-build/build/src" && BUILDMODE="static" STATIC_CC="/run/current-system/sw/bin/cc -O2 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 --target=x86_64-unknown-linux-gnu" TARGET_AR="/run/current-system/sw/bin/ar rcus" TARGET_LD="/run/current-system/sw/bin/cc -O2 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 --target=x86_64-unknown-linux-gnu" TARGET_STRIP="/run/current-system/sw/bin/strip" TARGET_SYS="Linux" XCFLAGS="-fPIC" "make" "-e"

  --- stderr
  thread 'main' panicked at /home/bigpog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/luajit-src-210.5.6+9cc2e42/src/lib.rs:259:39:
  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by khvzak** [comment]
Do you have `make` installed? Unfortunately this is LuaJIT requirements which has non-trivial build system

**Comment by BIGNARF** [comment]
> Do you have `make` installed? Unfortunately this is LuaJIT requirements which has non-trivial build system

Shoot, I knew I was forgetting something. That was it ,Thanks.
