### ISSUE TITLE
Hello, is it possible for mlua to write a dll module for standard lua5.3 or lua5.4.

### ISSUE THREAD

**Issue by a17022** [mlua-rs/mlua#380]
I used this example in my MLUA project, and the compiled luajit version of the DLL works fine, while standard 5.3 and 5.4 give errors

Add to Cargo.toml :
[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.9.1", features = ["lua54", "module"] }
lib.rs :

use mlua::prelude::*;

fn hello(_: &Lua, name: String) -> LuaResult<()> {
    println!("hello, {}!", name);
    Ok(())
}

#[mlua::lua_module]
fn my_module(lua: &Lua) -> LuaResult<LuaTable> {
    let exports = lua.create_table()?;
    exports.set("hello", lua.create_function(hello)?)?;
    Ok(exports)
}

**Comment by khvzak** [comment]
> while standard 5.3 and 5.4 give errors

could you show what error are you getting exactly?

**Comment by a17022** [comment]
> > while standard 5.3 and 5.4 give errors
> 
> could you show what error are you getting exactly?

Thanks for your reply!
...
require（'my_module')
Errors:
![Uploading 20240315011230.png…]()

**Comment by a17022** [comment]
> > while standard 5.3 and 5.4 give errors
> 
> could you show what error are you getting exactly?

Thanks for your reply!
...

environment variable :
LUA_LIB = C:\Lua5.4\
LUA_LIB_NAME = lua54
LUA_LINK = static
MLUAPKG_CONFIG = dylib

cargo build :
--------------------------------------------------------------------------------
PS C:\Users\MrBug\RustroverProjects\my_module> cargo build
   Compiling proc-macro2 v1.0.79
   Compiling unicode-ident v1.0.12
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling cc v1.0.90
   Compiling pkg-config v0.3.30
   Compiling memchr v2.7.1
   Compiling once_cell v1.19.0
   Compiling rustc-hash v1.1.0
   Compiling num-traits v0.2.18
   Compiling bstr v1.9.1
   Compiling mlua-sys v0.5.1
   Compiling quote v1.0.35
   Compiling syn v2.0.52
   Compiling mlua_derive v0.9.2
   Compiling mlua v0.9.6
   Compiling my_module v0.1.0 (C:\Users\MrBug\RustroverProjects\my_module)
    Finished dev [unoptimized + debuginfo] target(s) in 3.42s
PS C:\Users\MrBug\RustroverProjects\my_module>
--------------------------------------------------------------------------------

require（'my_module')
Errors :
--------------------------------------------------------------------------------
PS F:\Desktop\Lua5.4.2> .\Lua5.4.2.exe
Lua 5.4.2  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> require("my_module").hello("world")
error loading module 'my_module' from file 'F:\Desktop\Lua5.4.2\my_module.dll':
        The specified module could not be found.

stack traceback:
        [C]: in ?
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: in ?
>
--------------------------------------------------------------------------------

**Comment by a17022** [comment]
> > while standard 5.3 and 5.4 give errors
> 
> could you show what error are you getting exactly?

Problem solved, I didn't put "lua5x.dll" in my program directory   😆
