### ISSUE TITLE
Lack of Floored Division Support for Luau

### ISSUE THREAD

**Issue by CompeyDev** [mlua-rs/mlua#383]
- Floored division does not seem to work in mlua for luau. 
- Relevant APIs such as the `IDiv` metamethod, [are marked as lua only](https://docs.rs/mlua/latest/mlua/enum.MetaMethod.html#variant.IDiv). 
- The [luau RFC](https://github.com/luau-lang/rfcs/blob/master/docs/syntax-floor-division-operator.md#design) concerning this feature which has been marked as implemented, and functions as expected in the plain luau.

Is this intended? If so, why?

**Comment by khvzak** [comment]
> Floored division does not seem to work in mlua for luau.

could you show an example? it work fine for me:
```rust
lua.register_userdata_type::<i64>(|reg| {
    reg.add_meta_method("__idiv", |_, this, other: UserDataRef<i64>| {
        Ok(this / *other)
    })
})?;

lua.globals().set("a", AnyUserData::wrap(123i64))?;
lua.globals().set("b", AnyUserData::wrap(3i64))?;
lua.load("print(a // b)").exec()?; // prints 41
```

> Relevant APIs such as the IDiv metamethod, [are marked as lua only](https://docs.rs/mlua/latest/mlua/enum.MetaMethod.html#variant.IDiv).

right, thanks, I probably missed this moment. The `MetaMethod::IDiv` is direct equivalent of "__idiv" string so the change would be only cosmetic.

**Comment by CompeyDev** [comment]
You're right, it does work in mlua, I must've made a mistake on my end, apologies. Still, it would be a good idea to mark the enum variable usable for the luau feature. I'll be sure to close this issue once that is fixed.
