### ISSUE TITLE
Serializing from `serde_json::Value` to `mlua::Value` when the `arbitrary_precision` feature is enabled

### ISSUE THREAD

**Issue by gmryuuko** [mlua-rs/mlua#385]
When the `arbitrary_precision` feature is enabled in `serde_json`, the `Number` will be serialized as an `object`. Therefore, when I directly use `LuaSerdeExt` for serialization, I get a Lua table instead of the expected number.

```rust
let a = serde_json::Value::Number(1.into());
let lua = Lua::new();
let a = lua.to_value(&a).expect("");
dbg!(a);
```

```text
a = {
  ["$serde_json::private::Number"] = "1",
}
```

I have enabled `arbitrary_precision` because other parts of the program require this feature, but it is not needed here. So I added a new feature `ignore-serde-json-arbitrary-precision`, which converts this special table to a number.

https://github.com/gmryuuko/mlua/blob/281f8e7d585e66a1bf5ee496b0c0ba332cfb9cee/src/serde/ser.rs#L467-L475

Is there a better solution for this issue?

**Comment by khvzak** [comment]
I'll take a look! Never used `arbitrary_precision` feature before. 
I suppose a workaround (under `Option` flag) can be added to detect such usecase and convert string to number during serialization to lua value.

**Comment by khvzak** [comment]
I added a new option `detect_serde_json_arbitrary_precision`, see [example usage](https://github.com/mlua-rs/mlua/blob/master/tests/serde.rs#L702)
