### ISSUE TITLE
`AnyUserData::is` panics with unreachable code after being destructed with `AnyUserData::take`

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [mlua-rs/mlua#386]
`AnyUserData::is` panics with unreachable code if the internal `inspect` returns an error that isn't a `UserDataTypeMismatch`.
`inspect` calls `get_userdata_ref_type_id`, which propagates `Err(UserDataDestructed)` to the result of `inspect` when the underlying ref is that of destructed userdata.
Since `Err(UserDataDestructed)` is neither `Ok(())` or `Err(UserDataTypeMismatch)`, the `match` block in `is` chooses the `Err(_)` branch, which resolves to `unreachable!()`

This shouldn't work this way, since taking data out of a userdata ref doesn't clear the encapsulating lua ref from the state, meaning that ref still exists to be read in Rust as an `AnyUserData` and typechecked with `is`.
Fixing this should be as simple as removing the `Err(UserDataTypeMismatch)` branch and making the `Err(_)` branch return `false`.

**Comment by khvzak** [comment]
Thanks for the report! Fixed
