### ISSUE TITLE
Can module mode works with async? 

### ISSUE THREAD

**Issue by flea1lt** [mlua-rs/mlua#395]
The example shows a pretty example for starting module mode. 

But I wonder if the module mode works with the feature `async`? Is there any suggestion?

**Comment by khvzak** [comment]
Yes, module mode works perfect with `async` feature. You still need to use tokio or any other executor in your module.
Take a look to https://github.com/khvzak/haproxy-api-rs/blob/master/examples/async_serve_file/src/lib.rs as an example of async mode is module.
Also bear in mind that you will need to manually poll features from Lua OR integrate with external runtime used by app (eg. openresty or libuv).

**Comment by flea1lt** [comment]
Thanks!
