### ISSUE TITLE
Support Audio manipulation

### ISSUE THREAD

**Issue by RuizuKun-Dev** [mlua-rs/mlua#401]
Working with audio files is very challenging, rendering certain tasks either too difficult or seemingly impossible. This limitation inhibits developers from effectively automating their workflows, especially in the realm of audio management and manipulation.

Use Cases:
Workflow Automation: As a developer, I would like to enable efficient automation to streamline my workflow. However, the current implementation lacks the ability to automate tasks related to audio file management and manipulation effectively.

Audio Sprite Generation: My current project involves creating an audio sprite generator. This requires stitching together selected audio files and precisely mapping their timing in a JSON file. Unfortunately, the lack of robust audio handling capabilities has made this task exceedingly challenging.

note I have been struggling with this for a several weeks now trying to figure out how to use FFI and existing libraries with no avail, i'd greatly appreciate support for this

**Comment by khvzak** [comment]
I'm not sure I fully understand the issue.
Audio manipulation is not mlua scope. You are free to use any audio manipulation library in Rust and connect it to mlua.

**Comment by RuizuKun-Dev** [comment]
I apologize, I wasn't aware of that
