### ISSUE TITLE
Support UI

### ISSUE THREAD

**Issue by RuizuKun-Dev** [mlua-rs/mlua#402]
mlua is very versatile with a wide range of applications, but its current lack of native support for user interface development poses a significant limitation for us aiming to create interactive applications and graphical user interfaces.

**Comment by khvzak** [comment]
Feel free to use any UI library and connect it to mlua, which provides rich api for this. I'm happy to discuss more specific questions regarding integrating 3rd party libraries, if any.

**Comment by RuizuKun-Dev** [comment]
thank you, i'm not very familiar with Rust, Low level language concepts and connecting 3rd party tools


i'm currently using Lune to run my Luau scripts for automation and i'd really like the ability to create UI apps and do audio manipulation for Sound Sprite creations, etc
