### ISSUE TITLE
Serialization: Recursive table detection yields false positives

### ISSUE THREAD

**Issue by helgoboss** [mlua-rs/mlua#408]
When serializing a table, mlua detects if the table contains itself and fails in that case. The problem is that it's too strict. It detects a recursive table even if the table is just referenced multiple times, but doesn't contain itself. 

For example, mlua correctly deserializes the following code to a `Value`, even with `deny_recursive_tables == true`. But it fails to serialize the resulting `Value`.

```lua
local foo = {
    bla = 1,
}

return {
    a = foo,
    b = foo,
}
```

I think this can be trivially fixed by removing the table pointer from the hash set as soon as all pairs have been serialized in [this code](https://github.com/helgoboss/mlua/blob/8f3de8aa19ac7263297b080862c0a7a0ddb5de04/src/table.rs#L1104).

**Comment by khvzak** [comment]
Fixed, thanks
