### ISSUE TITLE
Send feature flag

### ISSUE THREAD

**Issue by lewisclark** [mlua-rs/mlua#411]
Is there anything I need to be careful of when using the `send` feature flag? It being locked behind a feature flag makes me wary that it has some side effects, as otherwise Send could be implemented by default?

**Comment by khvzak** [comment]
It adds `Send` requirements to Rust functions and userdata objects, which is not always desirable. Also don't be confused with `Sync`.

PS. Next mlua version will have `send` feature flag replaced with `sync` to allow easy integration with multithreading code.

**Comment by cppcoffee** [comment]
Added the `send` feature, then placed the Lua object into the BoxFeature. Compiler prompted an error:

```
*mut c_void cannot be shared between threads safely.
```

After reviewing the code, should we modify `*mut c_void` to `AtomicPtr`?

like:

```rust
pub struct LuaInner {
    state: AtomicPtr<ffi::lua_State>,
    // replace main_state: *mut ffi::lua_State,
    main_state: AtomicPtr<ffi::lua_State>,
    extra: Arc<UnsafeCell<ExtraData>>,
}
```

**Comment by cppcoffee** [comment]
The demo I use is as follows:

```
use mlua::{Lua, Result};

#[tokio::main]
async fn main() -> Result<()> {
    let s = "local a = 1";

    let boxed = Box::new(Box::pin(async move {
        let lua = Lua::new();
        lua.load(s).exec_async().await.unwrap();
    }));

    tokio::spawn(async move {
        boxed.await;
    });

    Ok(())
}
```

**Comment by cppcoffee** [comment]
I have submitted a PR for Lua support for Send/Sync. Please help review it.

The current usage is that a Lua structure cannot be executed across multiple threads. Each thread needs to be able to bind to one.

https://github.com/mlua-rs/mlua/pull/412

**Comment by cppcoffee** [comment]
Perhaps we can add a `LuaStatePtr` type to store the `ffi::lua_State` pointer to support the `Sync` type.

```
#[derive(Clone, Debug)]
struct LuaStatePtr(usize);

impl LuaStatePtr {
    #[inline(always)]
    fn from_ptr(ptr: *mut ffi::lua_State) -> Self {
        Self(ptr as usize)
    }

    #[inline(always)]
    fn as_ptr(&self) -> *mut ffi::lua_State {
        self.0 as *mut ffi::lua_State
    }
}
```

**Comment by khvzak** [comment]
v0.10 has proper support of `Send+Sync`
