### ISSUE TITLE
Get `registry_id` from `RegistryKey`

### ISSUE THREAD

**Issue by nferhat** [mlua-rs/mlua#422]
Hi! Currently using this library to integrate configuration and scripting into my program.

Some of my usage has signals (basically callbacks run on specific events), storing them in: `Vec<RegistryKey>` (where the registry key points to a function in the lua state)

If I want to remove a key, I don't want to rely on vector indexes in order to do so. A possible solution is to use `registry_id` to remove using `Vec::retain`

This property is private, one (hacky and bad) way to get it out is using:

```rust
fn get_registry_id(key: &mlua::RegistryKey) -> u64 {
    let mut hasher = std::hash::DefaultHasher::new();
    key.hash(&mut hasher);
    hasher.finish()
}
```

A getter would be much appreciated.

**Comment by nferhat** [comment]
UPDATE: That function `get_registry_id` does not get the registry id, just a hashed form

**Comment by khvzak** [comment]
I added `RegistryKey::id()` method in this [commit](https://github.com/mlua-rs/mlua/commit/c23fa5aa6ccb84146a96a0cdfbdf9117c35d9657) but note if you use `Lua::replace_registry_value` the underlying key can be changed.

In next major release I'm planning to take `&mut` instead when replacing values to better handle this.

**Comment by nferhat** [comment]
Thank you very much, exactly what I needed!

I don't use `replace_registry_value`, so changing registry ids should not be a concern (hopefully).

:+1:
