### ISSUE TITLE
Passing a Lua provided function makes Drop in mlua v0.10 code unwrap()

### ISSUE THREAD

**Issue by nospam2624** [mlua-rs/mlua#423]
This issue is for the v0.10 branch, commit 0a1f625. Where [Function][0] no longer requires a lifetime, like it does in v0.9.9.

Please consider this API struct. The smallest one I can come up with, allowing a Lua chunk to provide a function to later be called from Rust. 

```rust
#[derive(Clone,Default,mlua::FromLua)]
pub struct API {
    function: Option<mlua::Function>,
}

impl API {
    pub fn take_function(&mut self) -> Option<mlua::Function> {
        self.function.take()
    }
}

impl mlua::UserData for API {
    fn add_methods<'lua, M: mlua::UserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_method_mut("set_function", |_, this, function: mlua::Function| {
            this.function = Some(function);
            Ok(())
        });
    }
}
```

One might attempt to use the above struct like this:

```rust
fn main() {
    let lua = mlua::Lua::new();
    let api = API::default();
    lua.globals().set("api", api).unwrap();
    lua.load(b"api:set_function(function () print 'foo' end)".to_vec())
        .into_function().unwrap()
        .call::<_, mlua::Value>(()).unwrap();
    let mut api: API = lua.globals().get("api").unwrap();
    let function = api.take_function().unwrap();
    let _ = function.call::<_, ()>(());
    // let _ = function.call::<_, ()>(());
}
```

Doing so would lead to `foo` getting printed, even twice if uncommenting the last line. That is what I expect to happen.

However, the above code will also lead to an unwrap() in [WeakLua::lock()][1]. Which I assume is to be considered a bug, but please tell me if I'm just holding this thing all wrong.

[0]: https://docs.rs/mlua/0.9.9/mlua/struct.Function.html
[1]: https://github.com/mlua-rs/mlua/blob/0a1f625/src/lua.rs#L3381

**Comment by nospam2624** [comment]
Title changed, to clarify that the function does not actually even need to be called. Merely passing it will trigger the same behaviour.

**Comment by khvzak** [comment]
It's fixed now!

PS v0.10 is in active development and not really supposed to be used. I'm indeed considering removing `'lua` lifetime to simplify developers experience. There are still many things to do like optional `sync` support, solving open questions with `scope` / etc.

**Comment by nospam2624** [comment]
That was quick! Thank you!! I can verify that e3d138d indeed resolved this issue. (Fun fact: I did change the exact same function and committed it locally as "yolo: Hide bug!", but obviously didn't share that detail.)

PS. State of branch understood. Hence inclusion of _v0.10_ in the issue title. In my project, which is not yet ready for initial public release, a lifetime-less Function signature would sure simplify things. So I'll continue targeting it, hoping it will land. :slightly_smiling_face: 

Thanks again!
