### ISSUE TITLE
Returning an error in a rust function causes a un-unwindable panic

### ISSUE THREAD

**Issue by cheesycod** [mlua-rs/mlua#431]
I’m trying to run mlua in a tokio spawn local through a threadpool for luau

However, errors in rust function seems to cause un-unwindable panics due to my usage of panic = abort. Removing panic = abort doesn’t solve the issue but rather kills the thread spawned instead of panicking

code can be found at https://github.com/Anti-Raid/splashtail/blob/5b3310ff582e42041218aaf4b3821f3d09b8b12b/core/rust.templating/src/lang_lua/utils.rs#L42

**Comment by khvzak** [comment]
@cheesycod do you have a standalone example please to reproduce the issue? that I can run on my laptop

> will either be an un-unwindable panic

is there any specific message from the panic? Luau relies on external unwinding for exception handling so setting `panic=abort` is not supported atm.

**Comment by cheesycod** [comment]
> @cheesycod do you have a standalone example please to reproduce the issue? that I can run on my laptop
> 
> > will either be an un-unwindable panic
> 
> is there any specific message from the panic? Luau relies on external unwinding for exception handling so setting `panic=abort` is not supported atm.

1. The issue occurs with both panic=abort and without it. Without panic=abort, I get strange undefined behaviour such as dangling threads

Not really any standalone example since it is hard to reproduce outside of my discord bot, but well if you can create a discord application, here: https://github.com/Anti-Raid/splashtail/tree/255801d2a9ff7b39824ebd5f7e858891ad8b7e7a

The telltale sign of when this issue occurs is if you see a deadlock when editting a discord message. Then, the following is seen when run through gdb:

```
[Thread 0x7ffff47ef640 (LWP 391675) exited]
[Thread 0x7ffff49f6640 (LWP 391674) exited]
[Thread 0x7ffff5002640 (LWP 391671) exited]
[Thread 0x7ffff4dfe640 (LWP 391672) exited]
[Thread 0x7ffff5203640 (LWP 391670) exited]
[Thread 0x7ffff540a640 (LWP 391669) exited]
[Thread 0x7ffff560e640 (LWP 391668) exited]
[Thread 0x7ffff4bfa640 (LWP 391673) exited]
[Thread 0x7ffff580f640 (LWP 391667) exited]
[Thread 0x7ffff5a13640 (LWP 391666) exited]
```

**Comment by cheesycod** [comment]
@khvzak this issue isn’t so relevant in 0.10.0 thanks to your lovely change of making it sync (chefs kiss for that) so I no longer have to spawn 100 threads with a custom threadpool implementation and tokio local set

Will test it locally once I’m free though
