### ISSUE TITLE
require is broken on mlua 0.10

### ISSUE THREAD

**Issue by cheesycod** [mlua-rs/mlua#435]
In mlua 0.10, the ``require`` function no longer works::

Tested using both a ``cargo test`` and through the official ``repl`` example:

```
> require "math"
error: runtime error: [string "examples/repl.rs:20:23"]:1: module 'math' not found
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	[string "examples/repl.rs:20:23"]:1: in ?
> 
```

This should ideally not return an error and instead return from ``_G`` instead

**Comment by khvzak** [comment]
What Lua version?
