### ISSUE TITLE
Cannot use Chinese in lua file

### ISSUE THREAD

**Issue by xphost008** [mlua-rs/mlua#449]
I try to use like this:
```rust
let test = mlua::Lua::new();
test.load("print(\"你好，中国！\")").exec().unwrap();
```
it output mistaken code in Chinese.
Can you solve it?

**Comment by alerque** [comment]
I don't see a problem, at least testing with Lua 5.4. What Lua backend are you using?

```rust
#!/usr/bin/env rust-script
//! ```cargo
//! [dependencies]
//! mlua = { version = "0.9", features = [ "lua54" ] }
//! ```

fn main() {
    let test = mlua::Lua::new();
    test.load(r#"print("你好，中国！")"#).exec().unwrap();
}
```

Saved and `chmod 755`, then run, I get:

```console
$ ./foo.rs
你好，中国！
```

Note this looks identical to the input in my terminal. What are you seeing?

Also note I used an easier way of escaping the double quotes with a raw string in Rust, but I tried it your way too and got the same result.

**Comment by xphost008** [comment]
> 我没有看到问题，至少使用 Lua 5.4 进行测试。您使用的是哪个 Lua 后端？
> 
> ```rust
> #!/usr/bin/env rust-script
> //! ```cargo
> //! [dependencies]
> //! mlua = { version = "0.9", features = [ "lua54" ] }
> //! ```
> 
> fn main() {
>     let test = mlua::Lua::new();
>     test.load(r#"print("你好，中国！")"#).exec().unwrap();
> }
> ```
> 
> 保存并运行 ，我得到：`chmod 755`
> 
> ```
> $ ./foo.rs
> 你好，中国！
> ```
> 
> 请注意，这看起来与我的终端中的输入相同。你看到了什么？
> 
> 另请注意，我在 Rust 中使用了一种更简单的方法，即使用原始字符串转义双引号，但我也尝试了你的方法并得到了相同的结果。你也可以使用 Lua 的其他字符串分隔符，例如：
> 
> ```rust
>     test.load("print([[你好，中国！]])").exec().unwrap();
> ```

it look like this:
```rust
let test = mlua::Lua::new();
test.load(r#"print("你好，中国！")").exec().unwrap();
```
output:
```
浣犲ソ锛屼腑鍥斤紒
```
Maybe use GBK to read UTF-8 code. I guess

**Comment by eigeen** [comment]
I tried to run ```lua ./test.lua``` in the default powershell environment, and it outputs wrong characters as same as in mlua. It's not just mlua's problem.

**Comment by xphost008** [comment]
> I tried to run `lua ./test.lua` in the default powershell environment, and it outputs wrong characters as same as in mlua. It's not just mlua's problem.

but... I use lua ./test.lua if my file encoding is GBK, that output is normal, but I change encoding to UTF-8, that output wrong..
look below picture:
![image](https://github.com/user-attachments/assets/b39c4fac-d902-484c-9b2a-92a988cd211a)
the up output is UTF-8 encoding, the below output is GBK.
but I use mlua in Rust, however I use any encoding, it just output wrong..
so, that not my fault!

**Comment by xphost008** [comment]
I use mlua in RustRover, You can see my source:
This is get_file function:
![image](https://github.com/user-attachments/assets/b061a4f1-ff2a-4b8f-bbbf-a16b2b49db90)
This is my load_plugin function:
![image](https://github.com/user-attachments/assets/12253930-271c-4d60-875d-05a16df0121d)
You can watch it! thank you answer!

**Comment by eigeen** [comment]
Because the String encoding in Rust is always UTF-8, it is not affected by the source file encoding. You should set your terminal output encoding to UTF-8 in any way.

```sh
Active code page: 65001

C:\dev\mlua-test>cargo run  
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
     Running `target\debug\mlua-test.exe`
你好，中国！
```

**Comment by xphost008** [comment]
> Because the String encoding in Rust is always UTF-8, it is not affected by the source file encoding. You should set your terminal output encoding to UTF-8 in any way.
> 
> ```shell
> Active code page: 65001
> 
> C:\dev\mlua-test>cargo run  
>     Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
>      Running `target\debug\mlua-test.exe`
> 你好，中国！
> ```

Ha, whatever i run my rust file, I just need to run ```chcp 65001``` at first?
that sounds not good, my users think my software be Chinese support is not good..
However thank you! at least I know how to fix my software!

**Comment by eigeen** [comment]
However, `lua.exe` interactive  mode is right.

```sh
>> lua test.lua
浣犲ソ锛屼腑鍥斤紒
>> lua.exe
Lua 5.4.7  Copyright (C) 1994-2024 Lua.org, PUC-Rio
> print("你好，中国！")
你好，中国！
```

Maybe we can dynamically change the output according to the terminal code, like `println!`.

**Comment by eigeen** [comment]
> > Because the String encoding in Rust is always UTF-8, it is not affected by the source file encoding. You should set your terminal output encoding to UTF-8 in any way.
> > ```shell
> > Active code page: 65001
> > 
> > C:\dev\mlua-test>cargo run  
> >     Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
> >      Running `target\debug\mlua-test.exe`
> > 你好，中国！
> > ```
> 
> Ha, whatever i run my rust file, I just need to run `chcp 65001` at first? that sounds not good, my users think my software be Chinese support is not good.. However thank you! at least I know how to fix my software!

如果你软件使用mlua是为了嵌入脚本，尝试覆盖print函数，使用其他方式输出，例如`log::info!`或者`println!`，这应该是最合适的方案。mlua的实现可能是直接使用了lua库默认行为，才导致和直接运行lua的行为一样，源文件编码与控制台不匹配就会乱码。

**Comment by eigeen** [comment]
Here is an example for you to override the original `print` function:

```rs
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let test = mlua::Lua::new();
    test.globals().set(
        "print",
        test.create_function(|_, values: mlua::Variadic<String>| {
            println!("{}", values.join(", "));
            Ok(())
        })?,
    )?;

    test.load(r#"print("你好，中国！", 123, 456.789)"#).exec()?;

    Ok(())
}
```

**Comment by xphost008** [comment]
> Here is an example for you to override the original `print` function:
> 
> ```rust
> fn main() -> Result<(), Box<dyn std::error::Error>> {
>     let test = mlua::Lua::new();
>     test.globals().set(
>         "print",
>         test.create_function(|_, values: mlua::Variadic<String>| {
>             println!("{}", values.join(", "));
>             Ok(())
>         })?,
>     )?;
> 
>     test.load(r#"print("你好，中国！", 123, 456.789)"#).exec()?;
> 
>     Ok(())
> }
> ```
> 
> Note that it's a minimal example, if you want `print` behave like the original lua, you'll need more work to handle the various types, by accepting `mlua::Variadic<mlua::Value>`.

ok thanks! I know how to repair it!
