### ISSUE TITLE
How can I store a UserdataMutRef in rust?

### ISSUE THREAD

**Issue by CppCXY** [mlua-rs/mlua#450]
version: mlua 10.beta.2.

When I store a UserdataMutRef<LuaSocket> object through a method, I can no longer call LuaSocket's method in Lua. I receive the following error: 
```log
cause: BadArgument { to: Some("LuaSocket.accept"), pos: 1, name: Some("self"), cause: UserDataBorrowMutError } }
```

Is there any solution?

**Comment by khvzak** [comment]
You cannot have two RefMut objects as well as mix RefMut with Ref.
Borrowing rules are similar to Rust [RefCell](https://doc.rust-lang.org/std/cell/struct.RefCell.html).

You need to release the reference after accessing underlying object.

**Comment by CppCXY** [comment]
Thanks, I'll think of another way.
