### ISSUE TITLE
Communication of multiple lua states?

### ISSUE THREAD

**Issue by earlysun030201** [mlua-rs/mlua#456]
I've created a callback function table using lazy_static, and would like to use it to communicate between various lua states via events. When a function tries to call all the callback functions, it always prompts 'Lua instance is destroyed', and I think this might have something to do with the lua ownership, is it possible to divorce the mlua::Function calls from the lua ownership to achieve the above? Is it possible to divorce mlua::Function calls from lua ownership to accomplish the above?
```rust
use lazy_static::lazy_static;
use std::sync::Mutex;
use std::collections::HashMap;
use mlua::Function as LuaFunction;

lazy_static! {
    pub static ref LUA_CALLBACKS: Mutex<HashMap<String, Vec<LuaFunction>>> = Mutex::new(HashMap::<String, Vec<LuaFunction>>::new());
}
```

```rust
pub fn build_call(lua: &Lua) -> LuaFunction {
    let call = lua.create_function(|_, (e, value): (String, LuaValue)| {
        let callbacks_map = LUA_CALLBACKS.lock().unwrap();
        if let Some(callbacks) = callbacks_map.get(e.as_str()) { 
            for callback in callbacks {
                callback.call::<()>(value.clone())?;
            }
        }
        Ok(())
    }).map_err(|e| e.into_lua_err()).unwrap();

    return call;
}
```
<img width="672" alt="image" src="https://github.com/user-attachments/assets/1bb26cce-372d-460f-93b7-5295f0cd3d54">

**Comment by khvzak** [comment]
Easiest solution: move Lua instance to `lazy_static` block.
