### ISSUE TITLE
Using `getmetadata` in Lua on UserData from Rust returns a boolean.

### ISSUE THREAD

**Issue by SeanOMik** [mlua-rs/mlua#462]
I'm using the latest version of mlua, `0.9.9` for Lua 5.4 with the `send` feature enabled. I have a struct that implements `mlua::UserData` that is passed to a Lua script. When I try to get the metatable of the userdata in Lua, the method returns a `false` boolean value. Here is my lua script:
```lua
---Return the userdata's name from its metatable
---@param val userdata
---@return string
function udname(val)
    local tbl = getmetatable(val)
    if type(tbl) == "boolean" then
        error("what, got a boolean??: " .. tostring(tbl), 1)
    end

    return tbl.__name
end

local cube = world:request_res("../assets/cube-texture-embedded.gltf")
cube:wait_until_loaded()
print("Cube: " .. tostring(cube))
print("Loaded textured cube (" .. udname(cube) .. ")")
```

The scripts outputs:
```
Cube: LuaGltfHandle: 0x55d00d5f11c8
Script 'test.lua' ran into an error: runtime error: [string "scripting/src/lua/script.rs:39:13"]:7: what, got a boolean??: false
```

I'm confused on why `getmetatable` is returning a boolean. I didn't see anything related to it in the docs or in other issues, but maybe I missed it. I saw that the [lua reference manual](https://www.lua.org/manual/5.4/manual.html#pdf-getmetatable) states:
> If `object` does not have a metatable, returns nil. **Otherwise, if the object's metatable has a `__metatable` field, returns the associated value.** Otherwise, returns the metatable of the given object.

So does that mean the `__metatable` field on my UserData returns a boolean? Why would it? I'm not manually overriding it.

**Comment by khvzak** [comment]
Rust object metatable is a protected entity so access to it restricted. Otherwise incorrect usage can cause segfaults (eg. manipulating `__gc` method) which is violation of safety guarantees.
You can access the userdata metatable using [`AnyUserData::get_metatable`](https://docs.rs/mlua/latest/mlua/struct.AnyUserData.html#method.get_metatable) method to read `__name` field.

**Comment by SeanOMik** [comment]
Ah that makes sense. I ended up making my own `getmetatable` function that I could pass to lua:
```rust
let getmetatable_func = ctx.create_function(|lua, ud: AnyUserData| {
    // the userdata is left on the stack from `lua_getmetatable`, so that needs to be
    // included in the returns
    let (_ud, table): (mlua::AnyUserData, mlua::Table) = unsafe {
        lua.exec_raw(ud, |state| {
            mlua::ffi::lua_getmetatable(state, -1);
        })
    }?;
    
    Ok(table)
})?;

let globals = ctx.globals();
//globals.set("getmetatable2", getmetatable_func)?;
globals.set("getmetatable", getmetatable_func)?;
```

For some reason its not overriding the standard lua `getmetatable` though, so I'll probably just use `debug.getmetatable` which does what I expect. Thanks for the info!
