### ISSUE TITLE
Add try_borrow_mut to UserDataRef

### ISSUE THREAD

**Issue by negrel** [mlua-rs/mlua#468]
It would be nice to be able to mutably borrow a UserDataRef for a specified block.

```rust
methods.add_async_method("method", |_, udata, ()| async move {
  // Immutable borrow
  {
    udata.immut_op().await;
  }
  
  udata.borrow_mut().mut_op(); // or try_borrow_mut
  Ok(())
});
``` 

Currently, I'm forced to use `add_async_method_mut` and mutably borrow user data ref across await which can lead to double mutable borrow if this function is called twice concurrently.

I see in the source code that UserDataVariant provide these methods but isn't exposed and that a UserDataRef can't be converted to a UserDataRefMut.

Keep up the good works! 🙌

**Comment by khvzak** [comment]
To avoid holding a lock you can receive `AnyUserData` arg (via `add_async_function`) and then call [`borrow`](https://docs.rs/mlua/0.10.0-rc.1/mlua/struct.AnyUserData.html#method.borrow) or [`borrow_mut`](https://docs.rs/mlua/0.10.0-rc.1/mlua/struct.AnyUserData.html#method.borrow_mut) methods to obtain a reference.

**Comment by negrel** [comment]
ok thanks!
