### ISSUE TITLE
Make mlua::Error::ExternalError non Send + Sync when send feature is disabled

### ISSUE THREAD

**Issue by negrel** [mlua-rs/mlua#473]
Currently, it is not possible to pass a struct containing an `mlua::Value` to `mlua::Error::external()` as it requires `Send + Sync` marker traits.

IMO these restrictions shouldn't hold when `send` feature is disabled. A local fork with these changes returns no error when compiled with `luajit52`, `async`, `macros` features.

```
diff --git a/src/error.rs b/src/error.rs
index d18b1a3..0120a48 100644
--- a/src/error.rs
+++ b/src/error.rs
@@ -189,7 +189,7 @@ pub enum Error {
     /// Returning `Err(ExternalError(...))` from a Rust callback will raise the error as a Lua
     /// error. The Rust code that originally invoked the Lua code then receives a `CallbackError`,
     /// from which the original error (and a stack traceback) can be recovered.
-    ExternalError(Arc<dyn StdError + Send + Sync>),
+    ExternalError(Arc<dyn StdError>),
     /// An error with additional context.
     WithContext {
         /// A string containing additional context.
@@ -346,7 +346,7 @@ impl Error {
 
     /// Wraps an external error object.
     #[inline]
-    pub fn external<T: Into<Box<dyn StdError + Send + Sync>>>(err: T) -> Self {
+    pub fn external<T: Into<Box<dyn StdError>>>(err: T) -> Self {
         Error::ExternalError(err.into().into())
     }
 
@@ -400,7 +400,7 @@ pub trait ExternalError {
     fn into_lua_err(self) -> Error;
 }
 
-impl<E: Into<Box<dyn StdError + Send + Sync>>> ExternalError for E {
+impl<E: Into<Box<dyn StdError>>> ExternalError for E {
     fn into_lua_err(self) -> Error {
         Error::external(self)
     }
```

What do you think ? I can make a PR if you want.

**Comment by khvzak** [comment]
The `Error: Send + Sync` requirement is intentional mostly to be compatible with [`anyhow`](https://docs.rs/anyhow/1.0.91/anyhow/struct.Error.html#impl-From%3CE%3E-for-Error) definition:
```rust
impl<E> From<E> for Error
where
    E: StdError + Send + Sync + 'static,
```

Would be possible to use `RegistryKey` which is always `Send + Sync` instead of `Value` for your case ?

PS Another option (more realistic) would be adding a new feature flag, e.g. `error-send` to optionally relax this requirements.

**Comment by negrel** [comment]
> The Error: Send + Sync requirement is intentional mostly to be compatible with [anyhow](https://docs.rs/anyhow/1.0.91/anyhow/struct.Error.html#impl-From%3CE%3E-for-Error) definition:

Ok that's what I found out. Unfortunately, I can't use `RegistryKey` for my use case.

I see there is an `anyhow` feature, can it be used to strengthen requirements instead of relaxing ? Cargo features should be additive: https://doc.rust-lang.org/cargo/reference/features.html?highlight=additive#feature-unification

Let me know what you think

**Comment by khvzak** [comment]
I removed default requirement for `Send + Sync` and added `error-send` feature.
