### ISSUE TITLE
Feature Request: Delay the `register_userdata_type()` callback

### ISSUE THREAD

**Issue by sxyazi** [mlua-rs/mlua#482]
Currently, when calling `register_userdata_type<T>(|reg: UserDataRegistry| {})`, the closure runs immediately and registers fields/methods on `reg` even if the type `T` is never actually used in a Lua script:

https://github.com/mlua-rs/mlua/blob/c926327a6a4be7d31743f7c8474ecf6bd763b216/src/state.rs#L1307-L1310

In contrast, the registration process for non-external types that implement `impl UserData for T` only occurs when type `T` is actually used:

https://github.com/mlua-rs/mlua/blob/c926327a6a4be7d31743f7c8474ecf6bd763b216/src/state/raw.rs#L745-L762

It would be nice if `register_userdata_type()` could follow the same registration behavior as the `UserData` trait. 

In my case, I create multiple Lua instances across threads to run small scripts, and these scripts don't necessarily need all the types registered by `register_userdata_type()`, and it's hard to know in advance which `T`s will be needed as it largely depends on the logic of different scripts. Delaying registration until `T`s are actually needed would significantly improve initialization performance.

Beyond adding direct support for this in `mlua`, another workaround could be to create my own `create_userdata()` method that wraps `Lua::create_userdata()` - check whether type `T` has already been registered before calling `Lua::create_userdata()`, and if not, it would register `T` at that point. 

However, given the multi-threaded context, this would be considerably more complex since I need to maintain a registration status for each `T` in each thread.

**Comment by khvzak** [comment]
This would be a breaking change unfortunately, as of new callback restrictions: `MaybeSend + 'static`.

Why can't you use `impl UserData` for your types? Or

**Comment by sxyazi** [comment]
> This would be a breaking change unfortunately, as of new callback restrictions: `MaybeSend + 'static`.

Ah, that's really unfortunate. I've never used it to register non-static callbacks myself — I'm not entirely sure in what scenario that would be necessary, but it is definitely a breaking change. 

Maybe adding a new method like `register_userdata_type_lazy()` could be a compromise for this, though it would undoubtedly add extra maintenance overhead.

> Why can't you use `impl UserData` for your types?

Due to Rust's orphan rule, I can't implement `UserData` for external types — wasn't that the problem `register_userdata_type()` was meant to solve as well?

But I can live with creating newtype wrappers for them and implement the `UserData` trait for those wrappers, just a bit more of a hassle

**Comment by khvzak** [comment]
@sxyazi could you try the dev branch, will it make any difference?

**Comment by khvzak** [comment]
> However, the callbacks are still executed, which still causes a 10.7% performance loss:

During the callback execution, only heap allocation happens (e.g. `Box::new` and vector push). You could try to use [`jemallocator`](https://crates.io/crates/tikv-jemallocator) to reduce this time.

> Is it possible to delay the execution of these callbacks until they're actually needed as well?

Unfortunately this would require breaking changes,  as mentioned earlier, `Send + 'static`.

**Comment by sxyazi** [comment]
I see. 

Should I close this issue, or would you prefer to keep it to consider in the next breaking release?

**Comment by khvzak** [comment]
v0.10.2 is released.
I would close this for now.
