### ISSUE TITLE
Why is there a mutex guard in non-Send mode

### ISSUE THREAD

**Issue by cheesycod** [mlua-rs/mlua#497]
Hi, can the Reentrant Mutex in non send mode be removed entirely or made a NO-OP since it doesn't do anything as the VM is not even Send in the first place...

**Comment by khvzak** [comment]
There is no `ReentrantMutex` in non-send mode, only [dummy](https://github.com/mlua-rs/mlua/blob/6f6cda00990ab2b4db32c271424fda06a3be549e/src/types/sync.rs#L25) wrapper
