### ISSUE TITLE
Got Compiler warning "this function depends on never type fallback being `()`"  and "in edition 2024, the requirement `!: mlua::FromLua` will fail"

### ISSUE THREAD

**Issue by e1732a364fed** [mlua-rs/mlua#505]
My rust toolchain which caused this warning: 
rustc 1.83.0 (90b35a623 2024-11-26)
stable-x86_64-pc-windows-gnu

switching to this toolchain will not cause this warning:
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
stable-x86_64-pc-windows-msvc 

My code:

```rust
fn test1() -> mlua::Result<()> {
    let lua = Lua::new();
    lua.load("lua_text").eval()?;
    Ok(())
}

```

The whole prompt of the function is :

```
this function depends on never type fallback being `()`
this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
for more information, see issue #123748 <https://github.com/rust-lang/rust/issues/123748>
specify the types explicitly
`#[warn(dependency_on_unit_never_type_fallback)]` on by default
```

And there is another prompt for the "eval" part, it says:

```
in edition 2024, the requirement `!: mlua::FromLua` will fail
```

Changing `eval()` to `call(())` does not solve the issue.

Changing `eval` to `exec` does solve the issue.

Personally I think this is because of the newer rust version changed something, and I think it worth for some investigation or discussion.

**Comment by khvzak** [comment]
You need to provide output type:
```
lua.load("lua_text").eval::<()>()?;
```
Or alternative use `exec` method:
```
lua.load("lua_text").exec()?;
```

**Comment by e1732a364fed** [comment]
Wow, didn't think of that! You are so smart!
